name: Build LaTeX document

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: doc.tex
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-document
          path: doc.pdf
